# Manipulación de Arrays con Numpy

### 1- Arrays en Numpy

A diferencia de las listas de Python, cuando creamos un array en Numpy, existe la restricción de que todos los elementos tienen que ser del mismo tipo.
Esto hace que los arrays de numpy sean **más eficientes**.


In [1]:
import numpy as np

In [2]:
# Lista de python
l = [1, 4, 2, 5, 3]

# Arreglo de enteros instanciado a partir de una lista:
np.array(l)

array([1, 4, 2, 5, 3])

In [3]:
# Instanciamos un array a partir de una lista literal
a = np.array([1, 4, 2, 5, 3])

# Atributo que indica el tipo de datos de los elementos del array
a.dtype

dtype('int64')

In [4]:
# Si la lista de python tiene integers y floats, 
# el array de Numpy transforma todo en float para tener un solo tipo.
py_list = [3.14, 4, 2, 3]

np_array = np.array(py_list)

np_array

array([3.14, 4.  , 2.  , 3.  ])

In [5]:
np_array.dtype

dtype('float64')



Para crear arrays desde cero, lo más eficiente es hacerlo con los métodos propios de Numpy. Puedo crear arrays de ceros, de unos, de una secuencia, de valores aleatorios o de valores con una cierta **distribución estadística**, como por ejemplo la distribución normal.

##### Crear una Array de ceros

In [6]:
# Crear un array de longitud 10 lleno con ceros
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

#### Inicializar un array vacío

In [7]:
# Aloca un espacio en memoria pero no la inicializa
my_array = np.empty([2, 2])
my_array

array([[3.14, 4.  ],
       [2.  , 3.  ]])

#### Crear un Array que contiene números con distribución normal

In [8]:
# Puedo inicializar un array de números con distribución normal
# El primer parámetro es la media de la distribución
# El segundo parámetro es el desvío estándar
norm = np.random.normal(loc = 0, scale = 1, size = 12)

In [9]:
# También podemos crear una distribución normal 
# y asignarla a una matriz de dimensión n x m 
norm = np.random.normal(0, 1, size = (16,4))
norm

array([[-0.07821772, -0.12522622,  0.70049392, -0.54380299],
       [-0.81939721, -0.79471311,  0.97176923, -0.82527117],
       [-0.27117201,  2.10830348, -0.34723393,  0.02117605],
       [ 0.73151352, -0.32037566,  0.53213156, -1.36144197],
       [-0.13485801, -0.25122554, -0.46390652, -0.03057566],
       [-0.86243405, -0.83397903, -0.90542711, -1.028359  ],
       [-0.52509722, -0.38354813,  0.6897127 ,  2.89587721],
       [-0.40683937,  1.20464116, -2.25981349,  1.26683751],
       [ 0.91261388, -0.32743359,  0.65085009, -0.90907405],
       [ 2.46448062, -0.23493096,  1.06996115,  0.80605722],
       [-0.57374851,  1.67388961,  0.5252932 , -0.42834777],
       [-0.01855389,  0.56240696, -2.02601553, -0.51231714],
       [ 0.08818695, -0.48168066,  0.44083307,  0.57993486],
       [ 2.41496974, -1.79678757,  0.85744935, -0.02654011],
       [ 0.02852526,  0.93169641, -0.20238489, -0.69055851],
       [-1.14060269, -0.20553069, -0.36793851, -0.78184854]])

In [10]:
# Opcionalmente, puedo utilizar el método seed() 
# para que las elecciones aleatorias sean reproducibles
np.random.seed(0) 

norm = np.random.normal(0, 1, (3,4))
norm

array([[ 1.76405235,  0.40015721,  0.97873798,  2.2408932 ],
       [ 1.86755799, -0.97727788,  0.95008842, -0.15135721],
       [-0.10321885,  0.4105985 ,  0.14404357,  1.45427351]])


### Atributos de un array


In [11]:
# Array de 3 dimensiones con valores aleatorios entre 0 y 9
x3 = np.random.randint(10, size=(3, 4, 5))  
print(x3)

[[[8 1 5 9 8]
  [9 4 3 0 3]
  [5 0 2 3 8]
  [1 3 3 3 7]]

 [[0 1 9 9 0]
  [4 7 3 2 7]
  [2 0 0 4 5]
  [5 6 8 4 1]]

 [[4 9 8 1 1]
  [7 9 9 3 6]
  [7 2 0 3 5]
  [9 4 4 6 4]]]


In [12]:
print("x3 ndim :", x3.ndim)
print("x3 shape:", x3.shape)
print("x3 size :", x3.size)
print("dtype   :", x3.dtype)

# El tamaño de cada elemento del array. Depende del tipo de datos.  
print("itemsize:", x3.itemsize, "bytes") 

# El tamaño de todo el array. Se calcula de esta forma: itemsize * size
print("nbytes  :", x3.nbytes, "bytes") 

x3 ndim : 3
x3 shape: (3, 4, 5)
x3 size : 60
dtype   : int64
itemsize: 8 bytes
nbytes  : 480 bytes


## 2- Selección de elementos de un Array

Es un problema común querer seleccionar los elementos de un array de acuerdo a algún criterio. 
Numpy nos brinda tres formas de acceder <b> de forma eficiente </b> a los elementos de un array:
* Array Slicing
* Fancy Indexing
* Boolean Indexing

### 2-1 Array Slicing 

#### Slicing sobre una dimensión

El slicing es similar al de las listas de python [start:stop:step]. El índice stop no se incluye pero el start sí se incluye. Por ejemplo [1:3] incluye al índice 1 pero no al 3.
Funciona como un intervalo semicerrado [1,3).


In [0]:
# Sobre un array de una dimension
one_d_array = np.arange(10)
one_d_array

In [0]:
# Start = 1:  empezamos por el segundo elemento
# Stop: No está definido, entonces llegamos hasta el final.
# Step: El paso o distacia entre los elementos que voy a tomar.
one_d_array[1::2]  

In [0]:
# Para invertir el orden del array, podemos usar Step = -1
one_d_array[::-1]

In [0]:
# Si queremos hacer slicing en orden invertido

one_d_array[7:2:-1]  

#### Slicing sobre arrays de más  dimensiones


Con la misma lógica, se puede seleccionar en dos dimensiones

In [13]:
np.random.seed(0)
two_d_array = np.random.randint(10, size=(3, 4))
two_d_array

array([[5, 0, 3, 3],
       [7, 9, 3, 5],
       [2, 4, 7, 6]])

Cuando tenemos más de una dimensión, podemos hacer slicing sobre cada una de ellas separándolas con una coma. 

In [17]:
# Acceder a una columna
# Aquí los dos puntos ( : ) indican que accedemos a todos los elementos
# de cada fila y el cero después de la coma indica 
# que sólamente lo hacemos para la columna 0 (la primera).

#two_d_array[:, 0]
two_d_array[0:][0]

array([5, 0, 3, 3])

In [0]:
# Acceder a una fila
two_d_array[2, :]

In [0]:
# Otra forma de acceder a una fila
two_d_array[2]

In [0]:
# Un slice de dos columnas
two_d_array[:, 1:3]

In [0]:
# Todas las columnas listadas en orden inverso
two_d_array[:, ::-1]

### 2-2 Fancy Indexing

Esta técnica consiste en generar listas que contienen los índices de los elementos que queremos seleccionar y utilizar éstas para indexar.

In [0]:
# Pedimos 10 enteros entre 0 y 99
np.random.seed(2)
x = np.random.randint(100, size=10)
print(x)

Puedo acceder a un conjunto de elementos creando una lista con los índices que quiero acceder

In [0]:
ind = [3, 7, 4]
x[ind]

También se puede optar por una selección por fila y columna

In [0]:
# Creamos una matriz de 3 x 4
X = np.arange(12).reshape((3, 4))
X

In [0]:
# Un array de índices para acceder a filas determinadas
row = np.array([0, 2, 1, 0])
X[row]

In [0]:
# Accedemos a posiciones específicas de la matriz. 
# Los índices están dados por los arrays row y col
col = np.array([2, 3, 1, 2])
X[row, col]

### 2-2 Boolean Indexing

Esta técnica se basa en crear lo que se llama una "máscara booleana", que es una lista de valores True y False que sirve para seleccionar sólo los elementos cuyo índice coincide con un valor True.  

![_auto_0](attachment:_auto_0)

![_auto_0](attachment:_auto_0)

#### Ejemplo de aplicación boolean indexing: contar días de lluvia

Tenemos un dataset que representa la cantidad de precipitaciones del 2014 en la ciudad de Seattle

In [26]:
!head -n 2 Seattle2014.csv

head: cannot open 'Seattle2014.csv' for reading: No such file or directory


In [23]:
data = np.genfromtxt('Seattle2014.csv', skip_header=1, delimiter=',')

OSError: Seattle2014.csv not found.

In [0]:
# tomamos las precipitaciones
rain_s = data[:,3]

print ("shape:", rain_s.shape)
print (rain_s)

También exploramos este array utilizando un histograma. La funcionalidad la da la librería matplotlib

In [0]:
%matplotlib inline
import matplotlib.pyplot as plt

In [0]:
plt.hist(rain_s, bins = 40);

In [0]:
# Aplicamos una condición booleana sobre un array de Numpy y
# nos devuelve una nuevo array con True o False.

print (rain_s == 0)

**En lugar de hacer un loop** y definir un contador, vamos a describir los valores que nos interesan de este dataset utilizando Numpy:



In [0]:
# Veamos primero este comportamiento de los booleanos en python nativo
print("Suma de Booleans: ", True + False + True)

# Suma vectorizada de valores booleanos con Numpy,
# cuenta cantidad de ocurrencias del valor True en la lista
print("Suma de numpy: ", np.sum([True, False, True, True]))

In [0]:
print("Cantidad de días sin lluvia:      ", np.sum(rain_s == 0))
print("Cantidad de días con lluvia:      ", np.sum(rain_s != 0))
print("Cantidad de días con más de 100 cm de lluvia:", np.sum(rain_s > 100))
print("Cantidad de días con lluvia, pero no mayor a 100cm  :", np.sum((rain_s > 0) & (rain_s < 100)))

## 3 -  Numpy Universal Functions

Una de las ventajas de usar Numpy es que permite aplicar **operaciones vectorizadas**. 

Cuando determinadas operaciones se aplican sobre todos los elementos de un array, esta tarea se puede paralelizar y la computadora la completa en un tiempo mucho menor que si aplicásemos un loop y operásemos sobre cada uno de los elementos.

Para esto sirven las UFuncs (Universal Functions) de Numpy


##### Ejemplo: calcular el recíproco (1/x) de cada elemento de un array

In [0]:
# Definimos un array de gran tamaño
big_array = np.random.randint(1, 100, size=1000000)

# Enfoque tradicional

def compute_reciprocals(values):
    output = np.empty(len(values))
    for i in range(len(values)):
        output[i] = 1.0 / values[i]
    return output

%timeit compute_reciprocals(big_array)

In [0]:
# Enfoque Numpy

%timeit (1.0 / big_array)

In [0]:
%timeit np.divide(1.0, big_array)

### Agregación, Max y Min con Numpy

En Numpy se implementan de forma más eficiente los métodos que trabajan sobre los elementos del array:

In [0]:
# Aclaración: np.random nos da acceso a toda la funcionalidad del módulo random dentro del módulo numpy. 

big_array = np.random.rand(100000)

%timeit sum(big_array)
%timeit np.sum(big_array)

#### En arrays de varias dimensiones

In [0]:
my_array = np.random.random((3, 4))
M = my_array
M

In [0]:
# En Numpy, cuando se ejecutan funciones que reducen la dimensionalidad, axis representa el eje que se va a reducir
# En una matriz de dos dimensiones el 0 representa 
# el eje de las filas, y el 1 el eje de las columnas

print("Suma de toda la matriz: ", M.sum())
print("Mínimos de cada columna: ", M.min(axis=0))
print("Máximo de cada fila: ", M.max(axis=1))
print("Suma de cada fila: ", M.sum(axis=1))

## 4- Broadcasting: Otra forma de vectorizar

En conjunto con las ufuncs, el broadcasting es una forma de aplicar operaciones sobre los datos sin tener que escribir loops "for" en Python nativo que resultan más lentos.

Recordemos que cuando operamos sobre arrays de las mismas dimensiones, se pueden hacer operaciones eficientes elemento a elemento.



In [0]:
a = np.array([0, 1, 2])
b = np.array([5, 5, 5])
a + b

En el ejemplo de arriba, "a + b" es una operación eficiente porque "a" y "b" tienen la misma dimensionalidad y tamaño. 
Las reglas de "broadcasting" de Numpy, permiten que la operación siga siendo eficiente llevando los elementos involucrados a la misma dimensión y tamaño.

Veamos el siguiente ejemplo:

![image.png](attachment:image.png)

In [0]:
a + 5

Veamos un ejemplo con otras dimensiones:

In [0]:
#Recordemos el valor de "a"
a

In [0]:
# Ahora queremos sumar el vector "a" con una matriz de dos dimensiones, 
# de tamaño 3x3 que contiene todos valores 1.
M = np.ones((3, 3))


Gráficamente, esto es lo que sucede:
![image.png](attachment:image.png)